### ISSUE TITLE
Missing Badges

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-rgw-integration#75]
h3. Problem

This repo does not have badges like the other CORTX repos.
h3. Expected behavior

Badges should be present in top-level README.md
h3. How to reproduce

Look at top-level README.md
h3. Deployment information

Just using githu
h3. Additional information

Also, the README should contain some information about the purpose of this repo. [@ujjwalpl|https://github.com/ujjwalpl] , can you help with this please?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-30686. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

[https://github.com/Seagate/cortx-rgw-integration/pull/93] raised to add other Badges

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

Done

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. cortx-rgw-integration - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: Mukul Malhotra
* Component Build  :  5065 
* Release Build    :  5505  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/rockylinux-8.4/5505 

h3. Image Location  :  
*  cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5505
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-5505
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-5505
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-5505 
{panel}

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

Closed as Badges are added.
